#2433a05d8
w=open("test.txt","w")
w.write("Hello World \n")
w.close()
file=open("test.txt","a")
file.writelines(["These are the lines present in the file:\n","Hello\n","User\n"])
file.close()
file=open("test.txt","r")
x=file.read()
print(x)
file.close()
data=open("test.txt","r")
a=data.readline()
b=data.readline()
c=data.readlines()
print(a,b,c)