#24331a05d8
f=open("test.txt","w")
f.write("I'm Han \n")
f.write("Hello world \n")
f.flush()
print("data saved")
f.close()
f=open("test.txt","r")
print("Pointerposition: ",f.tell())
f.readline()
print(f.readline())
f.seek(0)
print("Pointer position: ",f.tell())
f.close()